#!/usr/bin/env node

const program = require('commander');
const build = require('./src/commands/build');
const clean = require('./src/commands/clean');
const package = require('./package.json');

program
  .version(package.version)
  .usage('[options] <file ...>')
  .description('Update your icon library from icomoon zip file');

program
  .command('build <icomoonZipFile>')
  .alias('b')
  .description('Uncompresses the zip file generated by icomoon and moves the files to the new destination.')
  .action((icomoonZipFile) => {
    build(icomoonZipFile);
  });

program
  .command('clean')
  .alias('c')
  .description('Cleans previously generated files.')
  .action(() => {
    clean();
  });

program.parse(process.argv);

if (program.args.length === 0) program.help();