const fs = require('fs-extra')
const chalk = require('chalk')

/**
 * Cleans previously generated files.
 *
 * @param {array} files
 */
const clean = (files) => {
  // todo: Check if files found
  return Promise
    .all(files.map(item => fs.remove(item)))
    .then(() => {
      console.log(chalk.bgGreen.black(' Files previosuly generated by icomoon removed '))
    })
}

module.exports = clean
