const fs = require('fs-extra')
const chalk = require('chalk')
const logger = require('../logger')
const config = require('../config')

/**
 * Cleans previously generated files.
 *
 * @param {array} files
 */
const clean = (files) => {
  // todo: Check if files found
  return Promise
    .all(files.map(item => fs.remove(item)))
    .then(() => {
      logger.info('Files previosuly generated by icomoon removed')
    })
}

module.exports = clean
